#!/usr/bin/env bash

export DATASTORE_SERVER_REPOSITORY_LOCATION='~/datastore/datastore-deployment/var/datastore-service-file-repo'
export SPRING_DATA_MONGODB_USERNAME='datastore'

export JAVA_HOME=/opt/jdk-16.0.2
export M2_HOME=/opt/apache-maven-3.8.7
