#!/usr/bin/env bash

export DATASTORE_SERVER_REPOSITORY_LOCATION='/home/osprey/datastore/datastore-deployment/var/datastore-service-file-repo'
export SPRING_DATA_MONGODB_USERNAME='datastore'

export JAVA_HOME=/usr/java/jdk-16.0.2
export M2_HOME=/opt/apache-maven-3.8.7

# --datastore.server.repository.location=/home/osprey/datastore-support/datastore-file-repository --datastore.service.influxdb.token=kBhCr542FKn8mQcL9JhUtqqs8mTdSY7mEydJKhtUvvV938q8zScCxjYiJLKXN8aLlKQZ0Bg3kBBGkKznH2d5Fg== --spring.data.mongodb.username=datastore --spring.data.mongodb.password=datastore
